language: ruby
sudo: false
rvm:
  - 2.2.5
  - 2.3.3
  - 2.4.0
  - ruby-head
branches:
  only:
    - master
before_install: gem install bundler -v 1.10.6
matrix:
  allow_failures:
    - rvm: ruby-head
